force-app/main/default/objects/Car__c/fields/Control__c.field-meta.xml
<CustomField>
    <fullName>Control__c</fullName>
    <description>Control of the car</description>
    <label>Control</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>car description</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <description>Market sell in Retail price</description>
    <label>MSRP</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Picutre_URL__c.field-meta.xml
<CustomField>
    <fullName>Picutre_URL__c</fullName>
    <description>picture URL</description>
    <label>Picutre URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Seats__c.field-meta.xml
<CustomField>
    <fullName>Seats__c</fullName>
    <description>0-9 seats</description>
    <label>Number Of Seats</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/carhubController.cls
public with sharing class carhubController {
   
    @AuraEnabled(Cacheable=true)
    public static List<Car__c> getCars(Filters filters){
        String key,whereClause='';
        Decimal maxPrice;
        String[] categories,makeType,criteria=new List<string>{};
        if(filters!=null){
            maxPrice=filters.maxPrice;
            categories=filters.categories;
            makeType=filters.makeType;
            if(!String.isEmpty(filters.searchKey)){
                key='%'+filters.searchKey+'%';
                criteria.add('Name LIKE : key');
            }
            if(filters.maxPrice>=0){
                criteria.add('MSRP__c <=:maxPrice');
            }
            if(filters.categories!=null){
                criteria.add('Category__c in :categories');
            }
            if(filters.makeType!=null){
                criteria.add('Make__c in :makeType');
            }
            if(criteria.size()>0){
                whereClause='WHERE '+String.join(criteria, ' AND ');
            }
        }
        string Query='SELECT id,Name,Category__c,Control__c,Description__c,Fuel_Type__c,Make__c,MSRP__c,Seats__c,Picutre_URL__c FROM Car__c '+whereClause +' WITH SECURITY_ENFORCED'+' ORDER BY Name';

        return Database.query(Query); 
        

    }

    public class Filters{
        @AuraEnabled public String searchKey {get;set;}
        @AuraEnabled public Decimal maxPrice {get;set;}
        @AuraEnabled public String[] categories {get;set;}
        @AuraEnabled public String[] makeType {get;set;}
    }

    @AuraEnabled(Cacheable=true)
    public static List<Car__c> getSimilarCars(Id carId,String[] makeType){

        return [SELECT id,Name,Category__c,Control__c,Description__c,Fuel_Type__c,Make__c,MSRP__c,Seats__c,Picutre_URL__c FROM Car__c where Make__c in :makeType and id !=:carId];
    }
}