force-app/main/default/objects/Task_Manager__c/Task_Manager__c.object-meta.xml
<CustomObject>
    <label>Task Manager</label>
    <nameField>
        <label>Task Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Manager__c/fields/isCompleted__c.field-meta.xml
<CustomField>
    <fullName>isCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCompleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/zwgToDoController.cls
public with sharing class zwgToDoController {
   
    @AuraEnabled(cacheable=true)
    public static List<Task_Manager__c> loadAllIncompleteRecords(){
    
        return [select Id,Name,Task_Date__c from Task_Manager__c where ownerId=:UserInfo.getUserId() and isCompleted__c=false WITH USER_MODE order by Task_Date__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Task_Manager__c> loadAllCompleteRecords(){
    
        return [select Id,Name,Completed_Date__c from Task_Manager__c where ownerId=:UserInfo.getUserId() and isCompleted__c=true WITH USER_MODE ORDER BY Completed_Date__c desc];
    }
}