force-app/main/default/objects/NewsApis_Setting__mdt/NewsApis_Setting__mdt.object-meta.xml
<CustomObject>
    <label>News Api setting</label>
    <pluralLabel>News Api settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/NewsApis_Setting__mdt/fields/category__c.field-meta.xml
<CustomField>
    <fullName>category__c</fullName>
    <label>category</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewsApis_Setting__mdt/fields/country__c.field-meta.xml
<CustomField>
    <fullName>country__c</fullName>
    <label>country</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewsApis_Setting__mdt/fields/endpointType__c.field-meta.xml
<CustomField>
    <fullName>endpointType__c</fullName>
    <label>endpointType</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewsApis_Setting__mdt/fields/version__c.field-meta.xml
<CustomField>
    <fullName>version__c</fullName>
    <label>version</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/trpNewsController.cls
public with sharing class trpNewsController {
    
    @AuraEnabled(cacheable=true)
    public static Map<String,Object> retrieveNews(){
        // Instantiate a new HTTP request, specify the method (GET) as well as the endpoint
       privateUrlClass pr=new privateUrlClass();
       String url=pr.getEndPoint();

       HttpRequest req = new HttpRequest();
       req.setEndpoint(url);
       req.setMethod('GET');

       Map<String,Object> responseJsonMap= new Map<String,Object>();
       string strResponse=null;
       // Send the request, and return a response
       try{
        Http http = new Http();
        HttpResponse res = http.send(req);
        if(res.getStatusCode()==200){
            strResponse=res.getBody();
        }
        else{
            throw new CalloutException(res.getBody());
        }
       }
       catch(Exception ex){
        throw ex;
       }
       
       if(!String.isBlank(strResponse)){
        responseJsonMap=(Map<String,Object>)JSON.deserializeUntyped(strResponse);
       }


       return (!responseJsonMap.isEmpty()) ? responseJsonMap:null;
        
    }

    public class privateUrlClass{

        private string getEndPoint(){
            String url='https://newsapi.org/';

            NewsApis_Setting__mdt mc = NewsApis_Setting__mdt.getInstance('Top_headlines_News');

            url=url+mc.version__c+mc.endpointType__c+'?country='+mc.country__c+'&category='+mc.category__c+'&apiKey='+mc.ApiKey__c;

            return url;
        }
    }
}